[project]
name = "vscode-debcontainer-jupyterlab"
version = "0.1.0"
description = "vscode-debcontainer-jupyterlab"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab==4.3.5",
]
